### ISSUE TITLE
13. REST API using OpenAPI, Flask & Connexions - app doesn't run

### ISSUE THREAD

**Issue by Chris-McQuiggan** [hmajid2301/medium#3]
when following the readme the app won't work.

1. the location to run flask from is incorrect. (should be from "medium\13. REST API using OpenAPI, Flask & Connexions\source_code\test-api\src\test_api")

2. there is a compile issue due to incorrect file names ( /web/controllers/pet_controller.py should be /web/controllers/pets_controllers.py)

3. there is an import issue inside pets_controllers.py

as this is a guide to learn the stack please can you supply a working example?

**Comment by hmajid2301** [comment]
Apologies for these issues I will look to resolve them this week.
